"""Draft answers to quesitos generated by mocked AI."""
from __future__ import annotations

from typing import Optional

from sqlalchemy import ForeignKey, String, Text, JSON, Float
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin, UUIDPrimaryKey


class QuestionDraftAnswer(Base, UUIDPrimaryKey, TimestampMixin):
    """Minuta de resposta a um quesito, gerada por IA mockada."""

    __tablename__ = "question_draft_answers"

    quesito_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("quesitos.id", ondelete="CASCADE"), nullable=False, index=True
    )
    case_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("cases.id", ondelete="CASCADE"), nullable=False, index=True
    )

    # Resposta gerada
    draft_text: Mapped[str] = mapped_column(Text, nullable=False)

    # Metadados da IA
    ai_model: Mapped[str] = mapped_column(String(100), default="mock-v1")
    confidence_score: Mapped[float] = mapped_column(Float, nullable=False)

    # Evidências utilizadas para gerar a resposta
    evidence_ids_used: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)

    # Controle
    generated_by_id: Mapped[Optional[str]] = mapped_column(
        String(36), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    review_notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    is_reviewed: Mapped[bool] = mapped_column(default=False, nullable=False)

    # Relacionamentos
    quesito: Mapped["Quesito"] = relationship("Quesito")  # noqa: F821
    case: Mapped["Case"] = relationship("Case")  # noqa: F821
    generated_by: Mapped[Optional["User"]] = relationship("User")  # noqa: F821

    def __repr__(self) -> str:
        return f"<QuestionDraftAnswer quesito={self.quesito_id} confidence={self.confidence_score:.2f}>"


from app.db.models.quesito import Quesito
from app.db.models.case import Case
from app.db.models.user import User

__all__ = ["QuestionDraftAnswer"]
