import type { DashboardSummary } from '../../types/dashboard'

export const mockDashboardData: DashboardSummary = {
  generatedAt: '2026-05-07T09:30:00-03:00',
  metrics: [
    {
      key: 'activeCases',
      label: 'Processos ativos',
      value: 42,
      detail: '18 em análise técnica',
      tone: 'work',
      trend: 'up',
      trendLabel: '+4 na semana',
    },
    {
      key: 'criticalDeadlines',
      label: 'Prazos críticos',
      value: 7,
      detail: '3 vencem em 48h',
      tone: 'warning',
      trend: 'up',
      trendLabel: '+2 hoje',
    },
    {
      key: 'openDiligences',
      label: 'Diligências abertas',
      value: 15,
      detail: '6 aguardam documentos',
      tone: 'attention',
      trend: 'flat',
      trendLabel: 'estável',
    },
    {
      key: 'pendingDocuments',
      label: 'Documentos pendentes',
      value: 28,
      detail: '11 com baixa confiança',
      tone: 'info',
      trend: 'down',
      trendLabel: '-5 desde ontem',
    },
    {
      key: 'processingFiles',
      label: 'Arquivos em processamento',
      value: 9,
      detail: 'OCR e classificação',
      tone: 'processing',
      trend: 'flat',
      trendLabel: 'fila normal',
    },
    {
      key: 'criticalLimitations',
      label: 'Limitações críticas',
      value: 4,
      detail: '2 impactam conclusão',
      tone: 'critical',
      trend: 'up',
      trendLabel: '+1 na semana',
    },
  ],
  alerts: [
    {
      id: 'alert-001',
      caseNumber: '0007421-13.2024.5.02.0001',
      subject: 'Prazo para entrega do laudo',
      category: 'Prazo crítico',
      dueLabel: 'Amanhã',
      severity: 'crítica',
      owner: 'Marina Lopes',
    },
    {
      id: 'alert-002',
      caseNumber: '0011088-45.2023.8.26.0100',
      subject: 'Diligência sem retorno da reclamada',
      category: 'Diligência aberta',
      dueLabel: '2 dias',
      severity: 'alta',
      owner: 'Rafael Nunes',
    },
    {
      id: 'alert-003',
      caseNumber: '1005920-77.2024.8.26.0053',
      subject: 'Holerites aguardando validação',
      category: 'Documento pendente',
      dueLabel: '3 dias',
      severity: 'média',
      owner: 'Carla Mendes',
    },
    {
      id: 'alert-004',
      caseNumber: '0001983-91.2025.5.15.0092',
      subject: 'Limitação técnica em cartão ponto',
      category: 'Limitação crítica',
      dueLabel: 'Hoje',
      severity: 'crítica',
      owner: 'Pedro Alves',
    },
  ],
}
